### ISSUE TITLE
Minimum requirements for MariaDB software

### ISSUE THREAD

**Issue by ReflexiveFox** [C6OI/Vint#3]
Can you mention the minimum acceptable version for MariaDB in the README file?

**Comment by C6OI** [comment]
You can find it in the [database.json](./Resources/database.json) file
![image](https://github.com/C6OI/Vint/assets/59257047/5bdede94-f9c9-4834-a13b-580ecf3fcdf9)

**Comment by ReflexiveFox** [comment]
i dont need to update it when i use an higher version right?

**Comment by C6OI** [comment]
right

**Comment by ReflexiveFox** [comment]
Ok thanks, i would like to have the README more beginner friedly :)
